version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: "test"
    IMAGE_TAG: "latest"
    AWS_DEFAULT_REGION: "ap-southeast-2"   # đổi theo region của bạn

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - ACCOUNT_ID=$(aws sts get-caller-identity --query account --output text)
      - REPOSITORY_URI=${ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${IMAGE_REPO_NAME}
      - aws ecr get-login-password --region ${AWS_DEFAULT_REGION} \
          | docker login --username AWS --password-stdin ${REPOSITORY_URI}

  build:
    commands:
      - echo Building Docker image...
      - docker build -t ${IMAGE_REPO_NAME}:${IMAGE_TAG} .
      - docker tag ${IMAGE_REPO_NAME}:${IMAGE_TAG} ${REPOSITORY_URI}:${IMAGE_TAG}

  post_build:
    commands:
      - echo Pushing image to ECR...
      - docker push ${REPOSITORY_URI}:${IMAGE_TAG}
      - echo Build completed.

artifacts:
  files: []
